# Use root/example as user/password credentials
version: "3.1"

services:
  db:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: testpassword
      MYSQL_DATABASE: bot_data
      MYSQL_USER: nick
      MYSQL_PASSWORD: testpassword
    ports:
      - 3306:3306
    expose:
      # Opens port 3306 on the container
      - "3306"
